spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devland
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true

  jackson:
    property-naming-strategy: SNAKE_CASE


api:
  security:
    token:
      secret: secret_key


springdoc:
  swagger-ui:
    # Caminho do seu CSS (o Spring serve arquivos da pasta static na raiz)
    css-url: /custom-swagger.css
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    use-root-path: true